In [2]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException

from bs4 import BeautifulSoup
import requests

import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

### 1. Scrape the details of most viewed videos on YouTube from Wikipedia.Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:

A)Rank
B) Name
C) Artist
D) Upload date
E) Views

In [7]:
#opening the most viewed youtube videos page on automated chrome browser
driver = webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(2)

In [10]:
rank = []
name = []
artist = []
upload_date = []
views = []

#to scrape Rank

Rank = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
for a in Rank:
    rank.append(a.text)
    
#to scrape Name

Name = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
for b in Name:
    name.append(b.text)


#to scrape Artist

Artist = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
for c in Artist:
    artist.append(c.text)
    
#to scrape date

Date = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
for d in Date:
    upload_date.append(d.text)
    
    
#to scrape views

view = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
for e in view:
    views.append(e.text)

In [11]:
print(len(rank), len(name), len(artist), len(upload_date), len(views))

30 30 30 30 30

In [12]:
Youtube = pd.DataFrame({'Rank':rank, 'Video Name': name, 'Artist': artist, 'Views(in Billions)': views, 'Upload Date': upload_date})
Youtube

,Rank,Video Name,Artist,Views(in Billions),Upload Date
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,13.48,"June 17, 2016"
1,2.,"""Despacito""[9]",Luis Fonsi,8.28,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[17]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.82,"October 8, 2016"
3,4.,"""Bath Song""[18]",Cocomelon - Nursery Rhymes,6.45,"May 2, 2018"
4,5.,"""Shape of You""[19]",Ed Sheeran,6.11,"January 30, 2017"
5,6.,"""See You Again""[22]",Wiz Khalifa,6.05,"April 6, 2015"
6,7.,"""Wheels on the Bus""[27]",Cocomelon - Nursery Rhymes,5.62,"May 24, 2018"
7,8.,"""Phonics Song with Two Words""[28]",ChuChu TV Nursery Rhymes & Kids Songs,5.52,"March 6, 2014"
8,9.,"""Uptown Funk""[29]",Mark Ronson,5.05,"November 19, 2014"
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[30]",Miroshka TV,4.99,"February 27, 2018"
10,11.,"""Gangnam Style""[31]",officialpsy,4.92,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""[36]",Get Movies,4.56,"January 31, 2012"
12,13.,"""Dame Tu Cosita""[37]",Ultra Records,4.46,"April 5, 2018"
13,14.,"""Axel F""[38]",Crazy Frog,4.09,"June 16, 2009"
14,15.,"""Sugar""[39]",Maroon 5,3.95,"January 14, 2015"
15,16.,"""Counting Stars""[40]",OneRepublic,3.89,"May 31, 2013"
16,17.,"""Roar""[41]",Katy Perry,3.89,"September 5, 2013"
17,18.,"""Baa Baa Black Sheep""[42]",Cocomelon - Nursery Rhymes,3.80,"June 25, 2018"
18,19.,"""Waka Waka (This Time for Africa)""[43]",Shakira,3.75,"June 4, 2010"
19,20.,"""Sorry""[44]",Justin Bieber,3.72,"October 22, 2015"
20,21.,"""Lakdi Ki Kathi""[45]",Jingle Toons,3.71,"June 14, 2018"
21,22.,"""Thinking Out Loud""[46]",Ed Sheeran,3.67,"October 7, 2014"
22,23.,"""Dark Horse""[47]",Katy Perry,3.60,"February 20, 2014"
23,24.,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.58,"January 26, 2018"
24,25.,"""Perfect""[49]",Ed Sheeran,3.56,"November 9, 2017"
25,26.,"""Let Her Go""[50]",Passenger,3.53,"July 25, 2012"
26,27.,"""Faded""[51]",Alan Walker,3.53,"December 3, 2015"
27,28.,"""Girls Like You""[52]",Maroon 5,3.50,"May 31, 2018"
28,29.,"""Shree Hanuman Chalisa""[53]",T-Series Bhakti Sagar,3.48,"May 10, 2011"
29,30.,"""Lean On""[54]",Major Lazer Official,3.48,"March 22, 2015"

In [13]:
Youtube.to_csv = ("ybmostviewedvideos.csv")

In [14]:
driver.close()

### 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. 

You need to find following details: 
A) Series 
B) Place 
C) Date 
D) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [3]:
#to open bcci.tv page on automated browser
driver = webdriver.Chrome()
driver.get('https://www.bcci.tv/')
time.sleep(2)

In [4]:

# to click on close button for pop-up
ad = driver.find_element(By.XPATH, '//button[@class="close-button page-close"]')
ad.click()

In [8]:
international =driver.find_element(By.XPATH, '//div[@class="imw-tabs international-tabs"][1]/a[2]')
international.click()

In [10]:
search = driver.find_element(By.XPATH,'//div[@class="cSBListSearch"][1]/input[1]')
search.send_keys("India")

In [12]:
india =driver.find_element(By.XPATH, '//div[@class="cSBListItems ng-binding ng-scope"][1]')
india.click()

In [13]:
#match series

series = []

serie = driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for a in serie:
    series.append(a.text)

title = []

titl = driver.find_elements(By.XPATH,'//div[@class="match-tm-info teamLeft"]/div[1]' and '//div[@class="match-tm-info teamRight"]/div[1]')
for b in titl:
    title.append(b.text)
    
    
place = []

loc = driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
for c in loc:
    place.append(c.text)

date = []
dat = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for d in dat:
    date.append(d.text)
    
    
time = []
tm = driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for e in tm:
    time.append(e.text)

In [16]:
print(len(series), len(title), len(place), len(date),len(time))

110 110 110 110 110

In [21]:
bcci = pd.DataFrame({'Series':series, 'Match': title, 'Place': place, 'Date': date, 'Time': time})
bcci

,Series,Match,Place,Date,Time
0,ICC MENS WORLD CUP 2023,Afghanistan,"Arun Jaitley Stadium, Delhi","11 OCTOBER, 2023",2:00 PM IST
1,ICC MENS WORLD CUP 2023,Australia,"MA Chidambaram Stadium, Chennai","8 OCTOBER, 2023",2:00 PM IST
2,ICC MENS WORLD CUP 2023,Pakistan,"Narendra Modi Stadium, Ahmedabad","14 OCTOBER, 2023",2:00 PM IST
3,ICC MENS WORLD CUP 2023,Bangladesh,"Maharashtra Cricket Association Stadium, Pune","19 OCTOBER, 2023",2:00 PM IST
4,ICC MENS WORLD CUP 2023,New Zealand,"Himachal Pradesh Cricket Association Stadium, ...","22 OCTOBER, 2023",2:00 PM IST
...,...,...,...,...,...
105,ASIA CUP 2022,Afghanistan,"Dubai International Cricket Stadium, Dubai","8 SEPTEMBER, 2022",7:30 PM IST
106,ASIA CUP 2022,Sri Lanka,"Dubai International Cricket Stadium, Dubai","6 SEPTEMBER, 2022",7:30 PM IST
107,ASIA CUP 2022,Pakistan,"Dubai International Cricket Stadium, Dubai","4 SEPTEMBER, 2022",7:30 PM IST
108,ASIA CUP 2022,Hong Kong,"Dubai International Cricket Stadium, Dubai","31 AUGUST, 2022",7:30 PM IST
109,ASIA CUP 2022,Pakistan,"Dubai International Cricket Stadium, Dubai","28 AUGUST, 2022",7:30 PM IST

In [18]:
driver.close()

### 3. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ 
You have to find following details: 

A) Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 

Note: - From statisticstimes home page you have to reach to economy page through code.

In [11]:
#to open statistics time page on automated browser
driver = webdriver.Chrome()
driver.get('http://statisticstimes.com/')
time.sleep(2)

In [12]:
#click on economy dropdown
econ_drop = driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/button')
econ_drop.click()

In [13]:
#to click on india
india = driver.find_element(By.XPATH,'//a[@href="economy/india-statistics.php"]')
india.click()

In [15]:
#to select states of India
states = driver.find_element(By.XPATH,'//a[@href="india/indian-states-gdp.php"]')
states.click()

In [22]:
Rank = []
State = []
GSDP18 = []
GSDP20 = []
Share = []
GDP = []

In [23]:
#scrape for rank, state, gdp gsdp and share
rank = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[1]')
for a in rank:
    Rank.append(a.text)

state = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[2]')
for b in state:
    State.append(b.text) 
    
gsdp1 = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[4]')
for c in gsdp1:
    GSDP18.append(c.text)

gsdp2 = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[3]')
for d in gsdp2:
    GSDP20.append(d.text)
    
share = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[5]')
for e in share:
    Share.append(e.text)
    
gdp = driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div[1]/div/table/tbody/tr/td[6]')
for f in gdp:
    GDP.append(f.text)
    
    
print(len(Rank),len(State), len(GSDP18),len(GSDP20),len(Share),len(GDP))

33 33 33 33 33 33

In [24]:
#to create Dataframe
statistics = pd.DataFrame({'Rank': Rank,'State': State, 'GSDP(18-19)-at current prices':GSDP18,
                           'GSDP(19-20)-at current prices' :GSDP20,'Share(18-19)':Share,'GDP($ billion)':GDP})
statistics

,Rank,State,GSDP(18-19)-at current prices,GSDP(19-20)-at current prices,Share(18-19),GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [25]:
#converting to csv file
statistics.to_csv('ws4statisticstimes.csv')

In [35]:
driver.close()

### 4. Scrape the details of trending repositories on Github.com. Url = https://github.com/ 

You have to find the following details: 

A) Repository title 
B) Repository description 
C) Contributors count 
D) Language used 

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [36]:
#to open github main page
driver = webdriver.Chrome()
driver.get('https://github.com/')
time.sleep(2)

In [37]:
# click on menu  button 
menu = driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/header/div/div[1]/div[2]/button/span/span")
menu.click()

In [38]:
#selct open source
open_source = driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
open_source.click()

In [39]:
#click on trending pages
trending = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [40]:
title = []
description = []
con_count = []
language = []

#to scrape title 
r_title=driver.find_elements(By.XPATH,'//a[@class="Link"]')
for a in r_title:
    title.append(a.text)
    
#to scrape url of all repository
r_URL = []
url_tags=driver.find_elements(By.XPATH,'//a[@class="Link"]')
for t in url_tags:
    r_URL.append(t.get_attribute('href'))
    
#to scrape desscription, contributor count, language used
for t in r_URL:
    driver.get(t)
    time.sleep(5)
    
    try:
        desc=driver.find_element(By.XPATH,'//p[@class="f4 mb-3 "]')
        description.append(desc.text)
    except NoSuchElementException:
        description.append('-----')
        
        
    try:
        count=driver.find_element(By.XPATH,'//*[contains(text(),"   Contributors")]/span')
        con_count.append(count.text)
    except NoSuchElementException:
        con_count.append('-----')
    

    try:
        lang =  driver.find_element(By.XPATH,'//li[@class="d-inline"]')
        language.append(lang.text.replace('\n','  '))
    except NoSuchElementException:
        language.append('-----')

In [41]:
print(len(title),len(description),len(con_count),len(language ))

25 25 25 25

In [42]:
github = pd.DataFrame({'Repository title': title,'Repository description' :description,'Contributors count':con_count,'Language used':language})
github

,Repository title,Repository description,Contributors count,Language used
0,spdustin / ChatGPT-AutoExpert,🚀🧠💬 Supercharged Custom Instructions for ChatG...,2,Python100.0%
1,PWhiddy / PokemonRedExperiments,Playing Pokemon Red with Reinforcement Learning,3,Jupyter Notebook98.4%
2,LazyVim / LazyVim,Neovim config for the lazy,96,Lua100.0%
3,ton-community / tact-challenge,-----,4,TypeScript100.0%
4,pi-hole / pi-hole,A black hole for Internet advertisements,220,Shell83.7%
5,TheAlgorithms / Python,All Algorithms implemented in Python,"1,087",Python100.0%
6,huggingface / text-embeddings-inference,A blazing fast inference solution for text emb...,-----,Rust80.6%
7,awesome-selfhosted / awesome-selfhosted,A list of Free Software network services and w...,"1,262",-----
8,gorhill / uBlock,uBlock Origin - An efficient blocker for Chrom...,105,JavaScript88.0%
9,practical-tutorials / project-based-learning,Curated list of project-based tutorials,104,-----
10,adrianhajdin / travel_ui_ux,Build and Deploy a Fully Responsive Modern UI/...,-----,TypeScript85.8%
11,calcom / cal.com,Scheduling infrastructure for absolutely every...,463,TypeScript95.1%
12,nvim-lua / kickstart.nvim,A launch point for your personal nvim configur...,70,Lua100.0%
13,hyprwm / Hyprland,Hyprland is a highly customizable dynamic tili...,180,C++97.2%
14,formbricks / formbricks,Open Source Surveys & Experience Management So...,102,TypeScript81.9%
15,iamcryptoki / snowden-archive,💥 A collection of all documents leaked by form...,-----,-----
16,LizardByte / Sunshine,Self-hosted game stream host for Moonlight.,79,C++81.3%
17,hkirat / docker-roadmap,-----,-----,JavaScript59.7%
18,doocs / leetcode,🔥LeetCode solutions in any programming languag...,124,Java23.3%
19,hustvl / 4DGaussians,4D Gaussian Splatting for Real-Time Dynamic Sc...,4,Python93.8%
20,topjohnwu / Magisk,The Magic Mask for Android,267,C++41.0%
21,qarmin / czkawka,"Multi functional app to find duplicates, empty...",56,Rust63.0%
22,nodejs / nodejs.org,The Node.js® Website,693,TypeScript51.6%
23,geekan / MetaGPT,🌟 The Multi-Agent Framework: Given one line Re...,35,Python99.7%
24,CleverRaven / Cataclysm-DDA,Cataclysm - Dark Days Ahead. A turn-based surv...,"1,922",C++96.2%

In [43]:
github.to_csv('ws4trendingrepo.csv')

In [46]:
driver.close()

### 5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ 

You have to find the following details: 

A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board 
 
 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [52]:
#to open billboard page
driver = webdriver.Chrome()
driver.get('http://www.billboard.com/')
time.sleep(2)

In [53]:
#to click on hot100 page
hot100 = driver.find_element(By.XPATH,'//div[@class="a-featured-chart-container-border"]/div/div[1]/div[1]/div/a')
hot100.click()

In [79]:
rank = []
s_name = []
a_name =[]
lwrank=[]
pkrank = []
woboard = []

In [80]:
#to scrape rank
score = driver.find_elements(By.XPATH,'//span[@class="c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet"]')
for a in score:
    rank.append(a.text)
    
  #to scrape song name  
song1 = driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet"]')
for b in song1:
    s_name.append(b.text)
songr = driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
for c in songr:
    s_name.append(c.text)
    
 # to scrape artist name
artist1 = driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]')
for d in artist1:
    a_name.append(d.text)
artistr = driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for e in artistr:
    a_name.append(e.text)
    
    #to scrape last week rank
lrank = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-row u-background-color-grey-lightest@mobile-max"]/li[3]')
for f in lrank:
    lwrank.append(f.text)

  #to scrape peak rank  
prank = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-row u-background-color-grey-lightest@mobile-max"]/li[4]')
for g in prank:
    pkrank.append(g.text)
    
    #to scrape week on board
board = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-row u-background-color-grey-lightest@mobile-max"]/li[5]')
for h in board:
    woboard.append(h.text)

In [81]:
print(len(rank),len(s_name),len(a_name), len(lwrank),len(pkrank),len(woboard))

100 100 100 100 100 100

In [82]:
#to create dataframe
billboard = pd.DataFrame({'Rank': rank,'Song name':s_name,'Artist name':a_name,'Last week rank':lwrank,'Peak rank':pkrank,'Weeks on board':woboard})
billboard

,Rank,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,1,Paint The Town Red,Doja Cat,1,1,9
1,2,Snooze,SZA,2,2,43
2,3,Cruel Summer,Taylor Swift,4,3,22
3,4,Fast Car,Luke Combs,3,2,28
4,5,3D,Jung Kook & Jack Harlow,-,5,1
...,...,...,...,...,...,...
95,96,Long Journey,Rod Wave,75,39,3
96,97,But I Got A Beer In My Hand,Luke Bryan,-,92,3
97,98,Rubicon,Peso Pluma,-,63,12
98,99,East Side Of Sorrow,Zach Bryan,95,18,6
99,100,Where She Goes,Bad Bunny,-,8,19

In [83]:
billboard.to_csv('ws4billboard.csv')

In [84]:
driver.close()

### 6. Scrape the details of Highest selling novels. 
#####  Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

A) Book name 
B) Author name 
C) Volumes sold 
D) Publisher 
E) Genre

In [2]:
#open the guardian page
driver = webdriver.Chrome()
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
time.sleep(2)

In [3]:
#to scrape top 100 highest selling books details
B_name = []
A_name = []
Volumes = []
Publ = []
Genre = []

#to scrape book name
bname = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
for a in bname:
    B_name.append(a.text)
    
 #to scrape author name   
aname = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
for b in aname:
    A_name.append(b.text)
    
    #to scrape volume sold
vol = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
for c in vol:
    Volumes.append(c.text)
    
    #to scrape publication details
publi = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
for d in publi:
    Publ.append(d.text)
    
    #To scrape genre details
gen = driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
for e in gen:
    Genre.append(e.text) 
    
    
print(len(B_name),len(A_name),len(Volumes),len(Publ),len(Genre))

100 100 100 100 100

In [5]:
#create dataframe
guardian = pd.DataFrame({'Book Name':B_name,'Author Name':A_name,'Volumes Sold':Volumes,' Publisher': Publ,'Genre':Genre})
guardian

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [6]:
guardian.to_csv = ('ws4guardian.csv')

In [7]:
driver.close()

### 7. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ 

You have to find the following details: 

A) Name 
B) Year span 
C) Genre 
D) Run time 
E) Ratings 
F) Votes

In [45]:
#open imdb page
driver = webdriver.Chrome()
driver.get('https://www.imdb.com/list/ls095964455/')
time.sleep(2)

In [9]:
#to scrape most watched series details 
name =[]   
year = []   
genre = []  
run = []  
ratings = []   
votes = []   

video = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/a')
for a in video:
    name.append(a.text)
    
span = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/span[2]')
for b in span:
    year.append(b.text)
    
serie = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[1]/span[5]')
for c in serie:
    genre.append(c.text)
    
time = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[1]/span[3]')
for d in time:
    run.append(d.text)
    
rate = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/div[1]/div[1]/span[2]')
for e in rate:
    ratings.append(e.text)
    
voting = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]')
for f in voting:
    votes.append(f.text)
    
print(len(name), len(year), len(genre), len(run),len(ratings),len(votes))

100 100 100 100 100 100

In [10]:
#create dataframe
imdb = pd.DataFrame({'Name':name,'Year Span': year, 'Genre': genre, 'Run time': run, 'Ratings': ratings,'Votes': votes})
imdb

,Name,Year Span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,211,902"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,282,010"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,049,450"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"308,407"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"267,378"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,915"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,992"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,762"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"44,062"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"268,510"

In [12]:
imdb.to_csv('ws4imdb.csv')

In [18]:
driver.close()

### 8. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ 
You have to find the following details: 

A) Dataset name 
B) Data type 
C) Task 
D) Attribute type 
E) No of instances 
F) No of attribute G) Year

 Note: - from the home page you have to go to the Show All Dataset page through code.

In [48]:
#to open archive.ics.uci automated page on browser
driver =webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')
time.sleep(2)

In [49]:
#to click on view all
viewall = driver.find_element(By.XPATH,'//a[@class="btn-primary btn"]')
viewall.click()

In [50]:
# to scrap URL of 66 pages
start =0
end = 66

Pr_URL = []

for page in range(start,end):
    url_tags= driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for t in url_tags:
        Pr_URL.append(t.get_attribute('href'))
    next_page = driver.find_element(By.XPATH,'//div[@class="my-4 flex flex-wrap items-center justify-end gap-4"]/div/button[2]')
    next_page.click()
    time.sleep(3)

ElementClickInterceptedException: Message: element click intercepted: Element <button class="btn-primary btn-sm btn" aria-label="Next Page" disabled="">...</button> is not clickable at point (1224, 261). Other element would receive the click: <div class="btn-group">...</div>
  (Session info: chrome=117.0.5938.152)
Stacktrace:
	GetHandleVerifier [0x00007FF761727D12+55474]
	(No symbol) [0x00007FF7616977C2]
	(No symbol) [0x00007FF76154E0EB]
	(No symbol) [0x00007FF761594E7B]
	(No symbol) [0x00007FF761593249]
	(No symbol) [0x00007FF761591018]
	(No symbol) [0x00007FF7615900D3]
	(No symbol) [0x00007FF761585DCF]
	(No symbol) [0x00007FF7615AF15A]
	(No symbol) [0x00007FF7615856E6]
	(No symbol) [0x00007FF7615AF370]
	(No symbol) [0x00007FF7615C7EF2]
	(No symbol) [0x00007FF7615AEF33]
	(No symbol) [0x00007FF761583D41]
	(No symbol) [0x00007FF761584F84]
	GetHandleVerifier [0x00007FF761A8B762+3609346]
	GetHandleVerifier [0x00007FF761AE1A80+3962400]
	GetHandleVerifier [0x00007FF761AD9F0F+3930799]
	GetHandleVerifier [0x00007FF7617C3CA6+694342]
	(No symbol) [0x00007FF7616A2218]
	(No symbol) [0x00007FF76169E484]
	(No symbol) [0x00007FF76169E5B2]
	(No symbol) [0x00007FF76168EE13]
	BaseThreadInitThunk [0x00007FF9744F257D+29]
	RtlUserThreadStart [0x00007FF9761EAA78+40]

In [51]:
len(Pr_URL)

657

In [52]:
Dname =[]
Dtype = []
task = []       
attritype = []
instances = []
attribute = []
year = []


for t in Pr_URL:
    driver.get(t)
    time.sleep(5)
    
    try:
        name = driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        Dname.append(name.text)
    except NoSuchElementException:
        Dname.append('-----')
        
    try:
        datatype = driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[1]/p')
        Dtype.append(datatype.text)
    except NoSuchElementException:
        Dtype.append('-----')
        
    try:
        dtask = driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[3]/p')
        task.append(dtask.text)
    except NoSuchElementException:
        task.append('-----')
        
    try:
        attype = driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[4]/p')
        attritype.append(attype.text)
    except NoSuchElementException:
        attritype.append('-----')
               
    try:
        inst = driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[5]/p')
        instances.append(inst.text)
    except NoSuchElementException:
        instances.append('-----')
        
    try:
        count = driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[6]/p')
        attribute.append(count.text)
    except NoSuchElementException:
        attribute.append('-----')
        
    try:
        date = driver.find_element(By.XPATH,'//div[@class="relative flex flex w-full items-center gap-4 bg-primary p-2"]/div[2]/h2')
        year.append(date.text)
    except NoSuchElementException:
        year.append('-----')

In [53]:
print(len(Pr_URL), len(Dname),len(Dtype),len(task),len(attritype),len(instances),len(attribute), len(year))

657 657 657 657 657 657 657 657

In [54]:
uci = pd.DataFrame({'Dataset name':Dname,'Data type': Dtype,'Task':task,'Attribute type':attritype,'No of instances':instances,
                    'No of attribute': attribute, 'Year': year})
uci

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Iris,Tabular,Classification,Real,150,4,Donated on 6/30/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,13,Donated on 6/30/1988
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,Donated on 4/30/1996
3,Wine,Tabular,Classification,"Integer, Real",178,13,Donated on 6/30/1991
4,Diabetes,"Multivariate, Time-Series",-,"Categorical, Integer",-,20,-----
...,...,...,...,...,...,...,...
652,Sattriya_Dance_Single_Hand_Gestures Dataset,Multivariate,Classification,-,1450,-,Donated on 7/21/2019
653,PMU-UD,Univariate,Classification,-,5180,9,Donated on 8/4/2018
654,EBL Domain Theories,-,-,-,-,-,-----
655,TamilSentiMix,"Multivariate, Text",Classification,Categorical,15744,-,Donated on 8/13/2023
656,TUNADROMD,Tabular,Classification,Integer,4465,242,Donated on 6/20/2023

In [55]:
uci.to_csv = ('ws4uci.csv')

In [56]:
driver.close()